export default {
    grass: 'green',
    water: 'blue',
    fire: 'orange',
    normal: '',
    electric: '',
    ice: '',
    fighting: '',
    poison: '',
    ground: '',
    flying: '',
    psychic: '',
    bug: '',
    rock: '',
    ghost: '',
    dark: '',
    dragon: '',
    steel: '',
    fairy: ''
}